// <auto-generated />
namespace CarrerTrack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameKey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameKey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702031205416_RenameKey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
